<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address</name>
   <tag></tag>
   <elementGuidId>9a178146-166f-473f-9705-b968f90ef296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#U25gO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/rpa1-field/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-name = 'labelAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c08949b-3767-406a-af0b-959736fcca2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelAddress</value>
      <webElementGuid>32672dde-f50c-460a-97cf-44bc0d37b8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>U25gO</value>
      <webElementGuid>35c12c50-0cc6-4b3b-8adf-929bfa8f9a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>U25gO</value>
      <webElementGuid>3f914961-ddf9-4bdd-845b-3851b4256a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>cfc0b738-51bf-4b01-ade9-ea6a8beb6e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;U25gO&quot;)</value>
      <webElementGuid>2f91a074-2397-41f9-9748-6f2c84a9a0cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='U25gO']</value>
      <webElementGuid>a15aa3db-8c24-4cdb-b59d-5e90d9154a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/rpa1-field/div/input</value>
      <webElementGuid>231779e0-db49-4e61-95fe-b59b986cd0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'U25gO' and @name = 'U25gO']</value>
      <webElementGuid>69367992-c284-481f-bd6c-5748845b5d16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
