<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Company Name</name>
   <tag></tag>
   <elementGuidId>75a86e15-1aac-4a65-8f08-ab118043979c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//div[2]/rpa1-field/div/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/rpa1-field/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-name = 'labelCompanyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80001789-8b19-4372-b899-bdeabc70c181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelCompanyName</value>
      <webElementGuid>9d3dedcf-774b-43f2-be39-7f9d1116b875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fnJCW</value>
      <webElementGuid>ced380fb-9f39-4244-bba3-0b11d6b862c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fnJCW</value>
      <webElementGuid>eda2cc63-0609-4381-baa3-b58c0f0038a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>7dacb4bd-e8f5-4da1-9895-42b2d8fe1991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fnJCW&quot;)</value>
      <webElementGuid>68c8ed4b-f523-4a4e-9f00-c0df7ba54966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fnJCW']</value>
      <webElementGuid>45673034-8d85-4086-a2a8-8be01188fa3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/rpa1-field/div/input</value>
      <webElementGuid>ecd09324-1743-4e5d-a025-99ff63ceda71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fnJCW' and @name = 'fnJCW']</value>
      <webElementGuid>d77f51fc-684a-4edd-843e-903cc6e8e61a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
