<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email</name>
   <tag></tag>
   <elementGuidId>1aab4456-19b7-4c65-9307-d4690a2a62b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IoWdo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[6]/rpa1-field/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-name = 'labelEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb7be190-334f-4d3c-baa5-a2c1d9377b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelEmail</value>
      <webElementGuid>1fcb999a-5a58-407f-965b-e5a3ab672d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IoWdo</value>
      <webElementGuid>d732abeb-fd6f-40ed-a178-5172db4264af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IoWdo</value>
      <webElementGuid>b86170b2-98b4-42e9-9b09-9affecf250f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>f84d2b22-f497-435b-b971-15e8baa9a1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IoWdo&quot;)</value>
      <webElementGuid>cb952718-99c9-4ab7-baf8-ea8c43d4f7d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IoWdo']</value>
      <webElementGuid>615734be-e8c5-4089-90c9-81e306293acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/rpa1-field/div/input</value>
      <webElementGuid>060d60af-dbdd-416a-944c-c2cd4df339ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IoWdo' and @name = 'IoWdo']</value>
      <webElementGuid>bfebc956-3421-41d3-afe2-47df87343ddc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
