<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Last Name</name>
   <tag></tag>
   <elementGuidId>19b9760d-11f2-4e13-96d2-91aa2584de9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//div[7]/rpa1-field/div/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'bSGNQ' and @name = 'bSGNQ']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-name = 'labelLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e3b58ed-5d03-40d7-bfd3-df1e8961156f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelLastName</value>
      <webElementGuid>fd315967-ef58-4730-a3a6-2b1b7810c9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bSGNQ</value>
      <webElementGuid>a58370e6-a9e5-4d8a-b0d9-a770163a1309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bSGNQ</value>
      <webElementGuid>0a2ad556-986f-4af9-ae5c-bd1882796333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>122edb89-99a0-4004-9d53-743037f69022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bSGNQ&quot;)</value>
      <webElementGuid>9929a5bf-aecf-4eaa-b3a2-32fcb785b136</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bSGNQ']</value>
      <webElementGuid>dfaee9ee-9029-46e7-a042-fae50df52d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/rpa1-field/div/input</value>
      <webElementGuid>2e6a4a3a-d3cc-4bfa-b142-91dd6bd29042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bSGNQ' and @name = 'bSGNQ']</value>
      <webElementGuid>17ec1be1-638a-4696-81ab-dc23e7a58477</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
