<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Role in Company</name>
   <tag></tag>
   <elementGuidId>123b87c6-fba4-4e4a-a541-652bc71d7564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BHgDK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'BHgDK' and @name = 'BHgDK']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-name = 'labelRole']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cb02b1e-ac9b-4ebd-b9c6-303115411123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>labelRole</value>
      <webElementGuid>7b2811bf-17d3-4dd6-abef-e0ab1fa244ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BHgDK</value>
      <webElementGuid>14229846-6c96-4a77-9283-b9891f6e81aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BHgDK</value>
      <webElementGuid>d8e7fcb7-41a3-4957-8be5-de474c24ed9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>94fa064b-7fe0-4f55-a9aa-bb6ebc814bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BHgDK&quot;)</value>
      <webElementGuid>d9a25f8c-04ed-4204-a30e-0d83422a76b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BHgDK']</value>
      <webElementGuid>aa25b806-09bf-40f4-9186-776c7e5f22f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>26f1c0f8-010a-4147-924f-8f7e0208f435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BHgDK' and @name = 'BHgDK']</value>
      <webElementGuid>e6e1bda9-79ae-40e9-a234-8465cc5cd195</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
