<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchHotel</name>
   <tag></tag>
   <elementGuidId>9c185d13-3cf5-41fe-9db6-2f7592699037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search_hotel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search_hotel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e690b844-b56c-49ff-adab-4345e7f9cd6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88de1bb8-c1b5-434e-a604-d07d1224c53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_hotel</value>
      <webElementGuid>351deb1b-ea2e-4b40-930f-e572ce19d63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search_hotel</value>
      <webElementGuid>7382e65e-84fa-4ce3-abdf-c5323f86346e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reg_button</value>
      <webElementGuid>1f5a9943-6e3c-473c-a743-6b5ef8387d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search Hotel</value>
      <webElementGuid>ce8d1c3f-97b3-4813-8c24-5464d98f8c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.location=&quot;SearchHotel.php&quot;</value>
      <webElementGuid>dd864a7b-119c-4756-b6eb-c35567f61d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_hotel&quot;)</value>
      <webElementGuid>f323391e-c29d-4866-b794-4078c9fab14a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search_hotel']</value>
      <webElementGuid>d836ff3c-39fc-41de-aa84-f1079831a4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='booking_form']/table/tbody/tr[19]/td[2]/input</value>
      <webElementGuid>ef8047e6-7000-4ea0-8c6c-faf893d5b301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[2]/input</value>
      <webElementGuid>83cacc7f-2274-4d33-aba9-cbf834811dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'search_hotel' and @id = 'search_hotel']</value>
      <webElementGuid>245ef44d-6527-428d-94e5-e787caf67829</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
