<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MobileSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f5291973-28f3-4a35-a155-040245fbf8a5</testSuiteGuid>
   <testCaseLink>
      <guid>61464919-3373-4992-8ccf-03a3dee24bee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MobileApplication/EriBankTC01_LoginPositive</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f0719d3-4db4-4cb2-9031-06bf18e6f1b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b60bc649-dc29-410f-bd9a-431c5713c9b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96b53efb-b872-436a-8a3c-d6f3ea6a23d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MobileApplication/EriBankTC02_MakePaymentPositive</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec9f62bc-7a54-499f-81ea-2dfd44bca06b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f459c0aa-9acd-49a6-8024-77695c923bbd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa3978cf-d93e-4872-b2d9-205fede5bcd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80cf1185-73c8-435f-a06a-09e7e7d8e5d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fe7949c-6170-4ff5-b1b3-15f5f08c6c04</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d283e240-336d-46b8-9a1a-2de8b4b1b006</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MobileApplication/EriBankTC03_LoginNegative</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb7d6bf8-9a00-4275-be3c-f0c12cf39e71</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b529de1-be4f-4482-beee-d9104be80439</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
