<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>See all buying options Submit</name>
   <tag></tag>
   <elementGuidId>819b65b8-aa52-469b-9dad-d29feb002393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='submit.deleteItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;submit.deleteItem&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a206cdac-0c24-49b9-8067-5058fec6f500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.deleteItem</value>
      <webElementGuid>dd631d59-5bad-4d07-bcc5-86a8d9ff2a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input a-declarative</value>
      <webElementGuid>0f95abec-9056-4077-b852-bb9ded56b428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ee270ad0-7c2a-4120-ba78-d01bad3455ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>delete-button-I2K1SS5ZBCQSAM-announce</value>
      <webElementGuid>f0730238-e4e3-4ec3-819a-0b507ffb3e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete-button-I2K1SS5ZBCQSAM&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input a-declarative&quot;]</value>
      <webElementGuid>744b51b7-0606-4aa2-856d-b8a165522180</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='submit.deleteItem']</value>
      <webElementGuid>dfa88641-4ebd-43fd-9b32-50cfbbd7fd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='delete-button-I2K1SS5ZBCQSAM']/span/input</value>
      <webElementGuid>21108fce-1108-426c-b412-5328cf9cc6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/span/span/span/input</value>
      <webElementGuid>5b783345-10b1-4efa-93a1-9afdfbad419a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submit.deleteItem' and @type = 'submit']</value>
      <webElementGuid>8ffc9f81-bd87-41be-957c-434fa313fdc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
