<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>QuantityForCart</name>
   <tag></tag>
   <elementGuidId>314793d0-04eb-4dfa-a776-8533274c0b02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='a-autoid-0-announce']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.a-dropdown-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a2f2d4dc-f195-47ef-abf4-165beb0a0767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-label</value>
      <webElementGuid>98f34da9-6121-4ff7-b6a6-3424e9181ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Qty:</value>
      <webElementGuid>8c11e192-1acc-4e59-ad55-3f8a861ba248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-0-announce&quot;)/span[@class=&quot;a-dropdown-label&quot;]</value>
      <webElementGuid>21a432e3-52b3-417c-a258-2ac99b818a7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-0-announce']/span</value>
      <webElementGuid>3e598f4d-69ae-4ba0-b8e6-3a90418778b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty:'])[1]/following::span[4]</value>
      <webElementGuid>3c90ee42-b20c-4c7c-81af-6c26c8aba59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gift options not available.'])[1]/following::span[9]</value>
      <webElementGuid>111dcf6b-9d7d-4e99-92a3-819b7199f6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Alchemist'])[4]/preceding::span[3]</value>
      <webElementGuid>50c2b4d0-8343-47cf-a36d-af2baabe9eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/span/span/span/span</value>
      <webElementGuid>b1947b4a-8ac9-43fd-baeb-27969eb6eab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Qty:' or . = 'Qty:')]</value>
      <webElementGuid>d083b4cc-e5a7-4151-a13b-b95e2303a455</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
