<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Spy_SelectMonthInBookAHotel</name>
   <tag></tag>
   <elementGuidId>cb901a7a-89c3-4951-bc1b-9e23e0d47f71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cc_exp_month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cc_exp_month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1c8c3a0a-a876-4395-93c2-fa982cabc6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cc_exp_month</value>
      <webElementGuid>05b70add-a25f-4871-8b85-fc56c6f30e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc_exp_month</value>
      <webElementGuid>b43d9dd6-8cb0-4946-a45b-d7c5b0f35751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_combobox2</value>
      <webElementGuid>46dd33d2-fd2a-4585-af98-443dd35e48a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            - Select Month -
            January
            February
            March
			April
			May
			June
			July
			August
			September
			October
			November
            December
          </value>
      <webElementGuid>62d9d214-8b83-4b6b-97ac-fef64646902a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc_exp_month&quot;)</value>
      <webElementGuid>545e351f-bfa6-4506-8c5a-caa654075db2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cc_exp_month']</value>
      <webElementGuid>bc154424-70d8-48c8-a2e0-1c11e95e06a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='book_hotel_form']/table/tbody/tr[17]/td[2]/select</value>
      <webElementGuid>0bb3831b-731a-442f-be7e-97c478917d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>051b2982-1065-461b-9f4b-b5341a6b3394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[2]</value>
      <webElementGuid>d77e6e2f-ef3a-4a83-a2d8-75976d25b940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[2]/select</value>
      <webElementGuid>073bb9f8-6973-4dd8-b015-33d9310c2b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cc_exp_month' and @id = 'cc_exp_month' and (text() = '
            - Select Month -
            January
            February
            March
			April
			May
			June
			July
			August
			September
			October
			November
            December
          ' or . = '
            - Select Month -
            January
            February
            March
			April
			May
			June
			July
			August
			September
			October
			November
            December
          ')]</value>
      <webElementGuid>3143a825-4e24-4fbe-9dee-ac0667490bce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
