<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Spy_SelectYearInBookAHotel</name>
   <tag></tag>
   <elementGuidId>a67e11d1-b0de-4a41-94a0-ac74a58b609d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cc_exp_year']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cc_exp_year</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4f219d36-6fc7-4cb9-9481-cdfd6353ddb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cc_exp_year</value>
      <webElementGuid>fbdf9363-07fc-423a-ad7b-5913524af3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc_exp_year</value>
      <webElementGuid>9b1a0a1b-8d3f-4e17-912c-a3f1f45af6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_combobox2</value>
      <webElementGuid>866baed1-8b2c-4b93-8509-a4a926ac6e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            - Select Year -
            2011
			2012
            2013
            2014
            2015
			2016
			2017
			2018
			2019
			2020
			2021
			2022
          </value>
      <webElementGuid>f876b5e4-b377-4963-8459-cea781e9355f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc_exp_year&quot;)</value>
      <webElementGuid>059cd32a-a6ee-45ce-b5d9-88cfdd3345c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cc_exp_year']</value>
      <webElementGuid>de845954-1260-4603-9f9c-de9b09022a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='book_hotel_form']/table/tbody/tr[17]/td[2]/select[2]</value>
      <webElementGuid>09e10c3c-1b66-42fa-ad2b-664b1d5eb1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[2]</value>
      <webElementGuid>ea457e3e-21e2-4cc6-b297-c7c1080ce55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[1]</value>
      <webElementGuid>d372be2b-70cd-464c-9267-17383bdeee4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>2ed41070-f585-4659-8ba2-a8a5547129b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cc_exp_year' and @id = 'cc_exp_year' and (text() = '
            - Select Year -
            2011
			2012
            2013
            2014
            2015
			2016
			2017
			2018
			2019
			2020
			2021
			2022
          ' or . = '
            - Select Year -
            2011
			2012
            2013
            2014
            2015
			2016
			2017
			2018
			2019
			2020
			2021
			2022
          ')]</value>
      <webElementGuid>d5cf0ef4-0b30-4c58-8451-d95043e0bc04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
