<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Linda Anderson</name>
   <tag></tag>
   <elementGuidId>1a174347-4442-4f53-b635-f16b3014b4e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div/revo-grid/div/div/revogr-viewport-scroll/div/div[2]/div/revogr-overlay-selection/revogr-data/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.rgCell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07836002-2aa0-4980-985b-791ef2bc1151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rgcol</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>112874db-1704-49e2-867e-00dd6bd26738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rgrow</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b83421eb-d2a4-4975-8d97-3c062fad7522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rgCell</value>
      <webElementGuid>00603cb8-6b9d-48d8-9c42-a56e2ba5712c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Linda Anderson</value>
      <webElementGuid>6e01adb6-527b-4503-9dc8-232bda50ef33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-paper-container&quot;]/div[@class=&quot;oxd-report-table --frame&quot;]/revo-grid[1]/div[@class=&quot;main-viewport&quot;]/div[@class=&quot;viewports&quot;]/revogr-viewport-scroll[@class=&quot;colPinStart&quot;]/div[@class=&quot;inner-content-table&quot;]/div[@class=&quot;vertical-inner&quot;]/div[@class=&quot;content-wrapper&quot;]/revogr-overlay-selection[1]/revogr-data[1]/div[@class=&quot;rgRow&quot;]/div[@class=&quot;rgCell&quot;]</value>
      <webElementGuid>a67e4d99-2c01-4b5f-8b40-f4555f086bed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div/revo-grid/div/div/revogr-viewport-scroll/div/div[2]/div/revogr-overlay-selection/revogr-data/div/div</value>
      <webElementGuid>4d7613f3-3750-401e-b7ac-eae251c1a57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee'])[1]/following::div[5]</value>
      <webElementGuid>ae85111c-a4e0-4eb6-87ee-0e31d11c19b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Entitlements (Days)'])[1]/preceding::div[3]</value>
      <webElementGuid>017f7471-9a76-4136-9b89-5655ef70ca15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Pending Approval (Days)'])[1]/preceding::div[6]</value>
      <webElementGuid>e3dfd205-1532-4347-8109-bcc97b3c221f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Linda Anderson']/parent::*</value>
      <webElementGuid>0cb3d0fa-f01d-4bd7-ab8d-ea033ed97f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//revogr-data/div/div</value>
      <webElementGuid>dab52be1-6469-4b45-ac70-1f7715b4b2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Linda Anderson' or . = 'Linda Anderson')]</value>
      <webElementGuid>2bafce92-b7b3-4320-8c86-72a511577686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
