<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AfterLogin__username_show</name>
   <tag></tag>
   <elementGuidId>4ad925f4-f339-49c3-9308-97327cc5ab70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='username_show']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#username_show</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c85370f-2d16-4ead-acd4-5ad2ee857721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6159c5ab-5579-48df-b143-aa86a7d2ee94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username_show</value>
      <webElementGuid>0268d651-7a24-46cd-9870-508db75b730c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>username_show</value>
      <webElementGuid>19be80c3-5bc4-4da6-8a57-ab42ca4d7ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_show</value>
      <webElementGuid>d4b0c25f-b4f5-4bcd-95da-7f27bf7f414e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Hello mokijoycosaxu!</value>
      <webElementGuid>eeb20122-8aed-4140-ae6d-8ce266937df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;username_show&quot;)</value>
      <webElementGuid>b73a949e-f987-4726-a813-f4047e06419e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='username_show']</value>
      <webElementGuid>26329c3c-a497-42bf-a194-25182d4a1616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9a5525df-2af5-4a23-9b90-90cc9c7964b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'username_show' and @id = 'username_show']</value>
      <webElementGuid>91f60ddc-7bf8-4a2c-83fb-41d99ead0c9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
