<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>WebSuite_OrangeHrm</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>3b51eda5-f51a-4525-bc0e-41155d48db77</testSuiteGuid>
   <testCaseLink>
      <guid>5e3dae34-af7b-4b62-9bb0-7bc9c11e980c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebApplication/OrangeHrm/OrangeHrmTC01_Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76e693b7-f428-4f8b-8438-542444732415</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f5983c6-d4aa-4e7f-a804-a59869373372</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>baf48dc8-686b-4b0a-b2e2-3f7dc6d1f709</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebApplication/OrangeHrm/OrangeHrmTC02_LeaveDetails</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1102c6f6-3b94-43cb-bd6f-da8500c64ec2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>138f9766-ece1-4814-bf1b-d68415962e37</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2ac7ee6-6b91-4ab4-979d-f6f3ae35d6a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebApplication/OrangeHrm/OrangeHrmTC03_LoginNegative</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5654a7e8-5ba8-4c17-b2f0-d913a94bd55f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>500896e0-cdc0-4185-af75-cf4a25a42966</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1826e44b-4a71-4111-a015-c1415d2bc7c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebApplication/OrangeHrm/OrangeHrmTC04_LoginFailed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>433d23d1-8e0a-459d-b337-317e61c4ed21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7979e999-be4d-4435-804a-9a9de266c4a0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
