<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>WebSuite_Amazon</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>da9df285-ccd8-482b-b39d-36c16d04ac87</testSuiteGuid>
   <testCaseLink>
      <guid>f5a72411-e711-4791-9c48-8df7d1739cd6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebApplication/Amazon/AmazonTC01_AddToCartPositive</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>622d7e13-250b-4dcc-a888-b331cf41717f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d9e2de0-585a-46d7-8026-2af0122e19c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed6a1884-520c-40ae-8ce7-ce2d146e8e01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>947a73d2-0347-4269-97cf-bba9d2c574a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f4027cae-67c1-4b36-8d49-2c2fb23e4827</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebApplication/Amazon/AmazonTC02_AddToWishlistPositive</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75f22adf-e010-4d16-9057-bdaa1bebc586</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa62e6c6-06a7-4c53-b21a-470dcbe4d914</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84dba023-ffe8-4cbb-83df-f18bb6791d07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21116a3a-9ea3-4627-924e-53fe5a73008f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>730a530d-ab13-483c-82ad-665df3e00bb5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebApplication/Amazon/AmazonTC03_SignInNegative</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16a8cae5-363e-4373-afbe-a0a342a81c59</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>665a41b6-b05f-422f-8d91-3cfb8d1feb95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebApplication/Amazon/AmazonTC04_SignInFailed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5740fced-b8de-47d2-afb9-e06b982f2e64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>384e969f-b331-476e-9664-12c0d1bcdfbf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
