<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>WebSuite_Adactin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>16a54dad-efaf-4e62-9152-0efe8689ecff</testSuiteGuid>
   <testCaseLink>
      <guid>90bd4eae-ac64-45c5-9320-1cd241e3f481</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebApplication/Adactin/AdactinTC01_VerifyLoginDetails</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d73a58b8-1cf7-4561-bc02-def1a3c9ba93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12baa223-35f2-4a10-a7de-45b8b03a4ebb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2cccedf5-c722-416a-a31a-4938cc75932c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebApplication/Adactin/AdactinTC02_VerifyLocationInSelectHotel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5db5f55-5eb9-458e-9484-858b555dd13a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5345248-5d69-472c-9aa2-c5b6d13bf781</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04c10855-4e86-435f-8a48-3b6b3565906f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1cbec29-b7e3-4752-a233-85221c492931</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e10fa39a-d2f3-4544-a082-2fce20aad70e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>74b4e05b-e7be-4582-86ef-f474f4585a2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebApplication/Adactin/AdactinTC03_VerifyDatesInSelectHotel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dfcb02c-5ea7-4a4a-8f11-a7e085a1a785</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3b00359-3b06-42e0-af2d-be2b1affc51c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f37cef44-a65c-4db6-b7fa-8ee4d6ff725a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e87b0c9-5233-4421-983a-e0b594dce456</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>575789dc-633d-4e3a-b91e-139bcc7a2031</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05870005-f9a6-4616-abbb-72069fb4101e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WebApplication/Adactin/AdactinTC04_VerifyLoginDetailsFailed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6564c706-1f00-4cfa-970d-58faaadaf364</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7d096f2-45d6-4842-bb16-1181efd71a50</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
