<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit</name>
   <tag></tag>
   <elementGuidId>ec91f9f8-c638-4bb7-93bb-a97476891229</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-to-wishlist-button-submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add-to-wishlist-button-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c9f22f2-08c4-433e-bd56-6aa9bbe40ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-to-wishlist-button-submit</value>
      <webElementGuid>55132d63-b706-4205-bbec-7a6ff4f9fcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.add-to-registry.wishlist</value>
      <webElementGuid>a4aaa85b-37fd-430e-9baf-8479164fbaaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add to Wish List</value>
      <webElementGuid>128a3083-0c83-4654-af52-67ec3edbbb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>atwl-splitbutton-main</value>
      <webElementGuid>a6fa660c-3110-42a0-a673-5e6b5a203531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>&lt;!-- If PartialItemStateWeblab is true then, showing different Add-to-wish-list tool-tip message which is consistent with Add-to-Cart tool tip message.  -->
       To Add to Wish List, choose from options to the left</value>
      <webElementGuid>d348d79c-0a0c-4bab-8683-cb93deb2015f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input a-declarative</value>
      <webElementGuid>5b99c7bc-4d99-470e-b7da-325d878fde16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ca2abf1d-89a2-4093-9190-2c8ac44ba02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add to Wish List</value>
      <webElementGuid>1316410b-9536-4752-8a27-d385de2f8a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>wishListMainButton-announce</value>
      <webElementGuid>06524ec2-f40d-45b8-9f34-6ff633207a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-wishlist-button-submit&quot;)</value>
      <webElementGuid>13ccf0e6-96be-4855-a278-25b92922844b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add-to-wishlist-button-submit']</value>
      <webElementGuid>9014172b-5763-470f-bed3-8506788259eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='wishListMainButton']/span/input</value>
      <webElementGuid>0286ff9e-7e11-422d-a5a7-73d3242ea996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>bd6f69c7-3c89-4b42-8840-6828d025413d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'add-to-wishlist-button-submit' and @name = 'submit.add-to-registry.wishlist' and @title = 'Add to Wish List' and @type = 'submit']</value>
      <webElementGuid>6a4ec791-4db5-4103-8459-64243bb7b291</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
