<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Close-buttonAfterAddingToCart</name>
   <tag></tag>
   <elementGuidId>40fa7113-009f-46a6-859c-0e25d8f98273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aod-close']/span/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.a-icon.a-icon-close.a-icon-medium.aod-close-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>196d9891-8bdd-4adb-8daa-b91be89b25fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon a-icon-close a-icon-medium aod-close-button</value>
      <webElementGuid>c6e681fc-180b-4d59-b7cd-57abf2b07533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>33208655-5e65-4f66-8ae5-831945c41a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>aod-close</value>
      <webElementGuid>88f1cbe6-7d0c-4ca8-923e-9ff239b0e5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aod-close&quot;)/span[@class=&quot;a-declarative&quot;]/span[1]/i[@class=&quot;a-icon a-icon-close a-icon-medium aod-close-button&quot;]</value>
      <webElementGuid>75781eba-8f25-4aa2-ad0b-9d313b6fa3eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aod-close']/span/span/i</value>
      <webElementGuid>224fe921-0965-4804-82a6-15ce92fdd4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>b9ace1e4-2663-4e99-b1b2-49bb7566b208</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
