<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ArrivalDateCheck</name>
   <tag></tag>
   <elementGuidId>d5b3e346-8fa8-44d5-8b05-5dff21d9e4c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='arr_date_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#arr_date_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'arr_date_0' and @type = 'text' and @value = '05/12/2022' and @class = 'select_text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23a140cc-477d-46fb-9c1b-078a0b38d864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>arr_date_0</value>
      <webElementGuid>f6b436ed-a297-4d4d-9fb6-fc03bc73c781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arr_date_0</value>
      <webElementGuid>4be4b2a6-a55a-4e6e-8f68-c1359b2cc6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9288cd20-8502-44d0-9a73-0a187e0e0e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>05/12/2022</value>
      <webElementGuid>521eb573-2a1d-4225-8616-109ebcb9e347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_text</value>
      <webElementGuid>dfeaab5f-c5d6-45c9-bffa-6806d21a767e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>disable_ctrlV()</value>
      <webElementGuid>c95c557e-d551-4c2c-b716-6b30826d4c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return Nothingonly(event)</value>
      <webElementGuid>31653769-4421-4cd6-b3fc-8f04e649dd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arr_date_0&quot;)</value>
      <webElementGuid>123b5479-9c91-4c04-9149-90622098066f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='arr_date_0']</value>
      <webElementGuid>cab8bdb6-7640-49e3-a541-b1b7b9e6ce55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='select_form']/table/tbody/tr[2]/td/table/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>8be19f56-5e8a-40b3-ae55-78ea233a517d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>33a0cb63-b55a-45e5-a0f0-a8684ddc4a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'arr_date_0' and @id = 'arr_date_0' and @type = 'text']</value>
      <webElementGuid>b4fcd9bd-5f60-4d44-afb6-c8a07cde1dc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
