<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DepartureDateCheck</name>
   <tag></tag>
   <elementGuidId>b09cbc29-da53-4940-880f-5128fa12717f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dep_date_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dep_date_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'dep_date_0' and @id = 'dep_date_0' and @type = 'text' and @value = '06/12/2022']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>775f6fab-83d4-4695-adec-a35d306c340e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dep_date_0</value>
      <webElementGuid>4b82e1e9-666d-481e-b91b-e714a9d177f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dep_date_0</value>
      <webElementGuid>4568c6e4-1b19-4ccf-ab55-cc7b9cb0923a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>063d5994-278c-41c7-9e8d-b48e9f235d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>06/12/2022</value>
      <webElementGuid>2ebbe9e9-f162-4080-8d07-9fe653dce20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_text</value>
      <webElementGuid>cd6c1de7-270f-4bae-b4f8-eb62f3db6773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>disable_ctrlV()</value>
      <webElementGuid>b63a21a5-652f-4c20-ac0e-c119bd1a47d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return Nothingonly(event)</value>
      <webElementGuid>8f99ca55-ca0f-4835-883b-72f4fb0e9780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dep_date_0&quot;)</value>
      <webElementGuid>412202ce-af3a-4428-9805-26704ac2927e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dep_date_0']</value>
      <webElementGuid>9c895281-bfe6-472b-8b3a-a23a49a78c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='select_form']/table/tbody/tr[2]/td/table/tbody/tr[2]/td[6]/input</value>
      <webElementGuid>33e82cda-6467-4290-bbc0-3fa95869444d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>30b0fba5-0050-4f56-a386-8f42622f3244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dep_date_0' and @id = 'dep_date_0' and @type = 'text']</value>
      <webElementGuid>684a9b40-7531-472e-adbb-528c4320b686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
