<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Price</name>
   <tag></tag>
   <elementGuidId>40bf0e78-0d1e-43b3-ba06-beeff9541571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='location_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#location_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c812d260-79d8-4a73-83b1-ecfe41589a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>location_0</value>
      <webElementGuid>32c9d63a-f57a-4fb5-82c5-3cf1c5df86fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>location_0</value>
      <webElementGuid>e7227a7b-3cd1-472e-b0a6-0fa6d74743ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81972eb3-da8f-4c35-9c2f-6a886e12520a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sydney</value>
      <webElementGuid>162b3bd3-33db-44c3-90a2-2d34c1d288bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_text</value>
      <webElementGuid>686a0511-685b-440a-ab49-8917c7d69c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>disable_ctrlV()</value>
      <webElementGuid>36492b92-d4fd-4016-9089-48bce0def2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return Nothingonly(event)</value>
      <webElementGuid>dca79956-dffa-4cf2-b1bc-c707712d74ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;location_0&quot;)</value>
      <webElementGuid>48232c86-c2c8-4f25-a514-6718bbbb7e99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='location_0']</value>
      <webElementGuid>77bae70b-b57c-4d00-9bda-20d60a47f6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='select_form']/table/tbody/tr[2]/td/table/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>567e65d7-043f-47ab-898b-efb96ac7d814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>a588697e-f861-4b48-8c3c-ab3b0649e3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'location_0' and @id = 'location_0' and @type = 'text']</value>
      <webElementGuid>19524bbc-695d-4f17-8937-db798cda1282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
